name: Build release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out repo
      uses: actions/checkout@v2
    
    - name: Run makefile
      run: make release
    
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          batch-dicom-extract-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}